# [START runtime]
runtime: nodejs
vm: true
# [END runtime]

# Temporary setting to keep gcloud from uploading node_modules
skip_files:
 - ^node_modules$

env_variables:
  API_PORT: 8080

manual_scaling:
  instances: 1
resources:
  cpu: .5
  memory_gb: 0.18
  disk_size_gb: 10
